#Test data
$file = "data/UniteU_Departments_20150710132002.csv"
$uid = { "id"	=> "1234" }
$csv_table = "departments"
$db_table = "categories"
$this_schema = {:KEY=>"id", :FIELDS=>{:id=>{:type=>"INTEGER", :rules=>"(KEY-NOTNULL-UNIQUE)", :format=>"int4", :default=>nil}, :name=>{:type=>"TEXT", :rules=>"(NOTNULL)", :format=>nil, :default=>nil}, :parent=>{:type=>"INTEGER", :rules=>nil, :format=>"int4", :default=>nil}, :description=>{:type=>"TEXT", :rules=>nil, :format=>nil, :default=>nil}, :img=>{:type=>"TEXT", :rules=>nil, :format=>"url", :default=>nil}, :rpro_id=>{:type=>"TEXT", :rules=>"(UNIQUE)", :format=>"alpha16", :default=>nil}, :google_shopping_map=>{:type=>"TEXT", :rules=>nil, :format=>nil, :default=>nil}}}
$category = {
  parent_id:"3011",
  dept_id:"3041",
  dept_name:"Women's Skis",
  dept_hyperlink:nil,
  dept_dept_target:"dept.asp, ",
  dept_prod_target:"product.asp, ",
  dept_disable_name:"1",
  dept_list_2_levels:nil,
  dept_list_product_levels:"1",
  dept_display_type:"4",
  dept_sort_type:"1",
  dept_sort_order:"2",
  dept_quick_dept_enable:nil,
  dept_quick_dept_level:nil,
  dept_short_description:nil,
  dept_description_top_1:nil,
  dept_description_top_2:nil,
  dept_description:nil,
  dept_description_2:nil,
  dept_image_1_file_scr:"PRODUCT",
  dept_image_1_file:"GDADAAAABJAMMFBHt.jpg",
  dept_image_1_width:nil,
  dept_image_1_height:"3",
  dept_image_1_h_align:"CENTER",
  dept_image_1_file_target_scr:"NONE",
  dept_image_1_file_target:nil,
  dept_image_1_file_target_alt:nil,
  dept_image_2_file_scr:"NONE",
  dept_image_2_file:nil,
  dept_image_2_width:nil,
  dept_image_2_height:nil,
  dept_image_2_h_align:"CENTER",
  dept_image_2_file_target_scr:"NONE",
  dept_image_2_file_target:nil,
  dept_image_2_file_target_alt:nil,
  rpro_dept_id:"OJACAAAAKPHBMGBH",
  dept_spanner_elements_per_page:nil,
  dept_meta:"<meta name =\"description\",
	content=\"Shop Women's Skis equipment and gear at Lee's Adventure Sports.\">",
  dept_rpro_dcs:nil
}
$productitem = {
  sku:"5621",
	pf_id:"PAAAIANDLLJGLPCE",
	attr_value1:"165-169",
	attr_value2:"GSTAR",
	attr_value3:nil,
	attr_value4:nil,
	attr_value5:nil,
	variant_enabled:"1",
	ship_info:nil,
	vendor_code:nil,
	order_code:"SIDEWINDER",
	price_level1:"16.99",
	price_level2:"16.99",
	price_level3:nil,
	price_level4:"16.99",
	price_level5:"16.99",
	price_level6:nil,
	price_level7:"16.99",
	price_level8:"16.99",
	price_level9:nil,
	cost:"7.75",
	out_orders:"0",
	orders_sent:nil,
	setback:"0",
	backorder:"0",
	inventory_level:"0"
}

$productgroup = {
  dept_id:"3535",
  sort_index:"326",
  pf_id:"PAIEIDHLAGLDEDMK",
  name:"The North Face Men's 2014 Ampere Crew",
  product_enable:"1",
  sort_order:"0",
  meta_tag_info:nil,
  short_description:nil,
  description:"<ECI><P><FONT size=4 face=Verdana>The North Face Men's 2014 Ampere Crew</FONT></P><P><FONT face=verdana>Train in a lightweight crew that’s crafted of extremely durable, wicking FlashDry-XD™ fibers and get fit without compromise. As you meet your fitness goals, the body mapped ventilation will keep you cool and dry during tough workouts. The hem dips slightly lower in the back for extra coverage when raising arms overhead to finish a set of sandbag presses.</FONT></P><P><FONT face=verdana><U>Features</U><BR>• Easy-care, lightweight fabric<BR>• Body-mapped ventilation<BR>• Set-in sleeves<BR>• Contrast topstitching<BR></FONT></P><P><FONT face=verdana><U>Specifications</U><BR>• Fabric: body: 120 g/m² 100% polyester knit jersey with FlashDry-XD™, Fabric: panel: 139 g/m² 100% polyester diamond knit piqué with FlashDry™ <BR>• Length from Center Back: 27”</FONT></P><P><FONT face=verdana><U>Mens Sizing<BR></U>(M) Neck: 16\". Chest: 39-41\". Waist: 32-34\". Sleeve Length: 34\"<BR>(L) Neck: 16.75\". Chest: 42-44\". Waist: 35-37\". Sleeve Length: 34.75\"<BR>(XL) Neck: 17.75\". Chest: 45-48\". Waist: 38-40\". Sleeve Length: 35.5\"</FONT></P>",
  enable_basket:"1",
  enable_compare:"0",
  enable_wish:"0",
  enable_quote:"0",
  enable_manual_quote:"0",
  show_price_1:"1",
  msrp_price:"0",
  list_price:"0",
  image_file:"PAIEIDHLAGLDEDMKt.jpg",
  image_width:nil,
  image_height:nil,
  show_image_1:"0",
  show_price_2:"1",
  sale_price:"0",
  sale_start:"03/07/99",
  sale_end:"03/07/99",
  image_2_file_scr:"PRODUCT",
  image_2_file:"PAIEIDHLAGLDEDMK.jpg",
  image_2_width:nil,
  image_2_height:nil,
  image_2_align:"CENTER",
  image_2_file_target_scr:"NONE",
  image_2_file_target:nil,
  image_2_file_target_alt:nil,
  ship_info:"0lb 0x0x0in box",
  ship_allow:"0",
  product_class:"default",
  vendor_code:"default",
  order_code:"default",
  info_attributes:nil,
  in_stock_msg:"1",
  out_stock_msg:nil,
  back_order_msg:nil,
  pos_product:"1",
  activation_date:nil,
  deactivation_date:nil,
  child_products:nil,
  storefront_code:"-1",
  allowpriceoverride:"FALSE",
  ignoreinventory:"FALSE",
  attr_label1:"Size",
  attr_label2:"Attribute",
  attr_label3:nil,
  attr_label4:nil,
  attr_label5:nil
}

$order = {
  webordernumber:"12784",
	shopper_id:"C21D0CE3450D4AC298B51297FE16A324",
	int_shopper_id:nil,
	billfname:"Eugene",
	billlname:"Nerus",
	billname:"Eugene Nerus",
	billaddr1:"1209 Norwalk Road",
	billaddr2:"apt 8",
	billcompany:nil,
	billcity:"Philadelphia",
	billstate:"PA",
	billzip:"19115",
	billcountry:"USA",
	billphone:"2673121101",
	billemail:"me@creativedd.com",
	cctype:"VISA",
	ccnumber:"4246XXXXXXXX6258",
	ccexpire:"06/18",
	authcode:"03320G",
	authdate:"2015-07-07T153110Z",
	sourcecode:nil,
	custom1:nil,
	custom2:nil,
	txntime:"11:31:11",
	txndate:"07/07/2015",
	shipfname:"Eugene",
	shiplname:"Nerus",
	shipname:"Eugene Nerus",
	shipaddr1:"318 Carson Ter",
	shipaddr2:nil,
	shipcompany:nil,
	shipcity:"Huntingdon Valley",
	shipstate:"PA",
	shipzip:"19006",
	shipcountry:"USA",
	shipphone:"2673121101",
	shipphoneus:"(267) 312-1101",
	shipemail:"me@creativedd.com",
	numberofpayment:"1",
	shipmethod:"Ground",
	orderbaseamt:"239",
	shippingandhandling:"0",
	tax:"0",
	discount:"0",
	ordertotal:"239",
	cybersourceflag:"SOK",
	cybersourcescore:"10",
	cyberscore_factors:"P^T^Y",
	cyberauth_cv_result:"M",
	cyberauth_auth_avs:"Y",
	cybersourcemsg:"Successful",
	cybersourcerequestid:"4362830704755000000000",
	payflowflag:"1",
	store_id:"0",
	tax_state_name:nil,
	tax_total_state_tax:"0",
	tax_district_name:nil,
	tax_total_district_tax:"0",
	tax_county_name:nil,
	tax_total_county_tax:"0",
	tax_city_name:nil,
	tax_total_city_tax:"0",
	tax_total:"0",
	subtotal:"23900",
	shipping_total:"0",
	handling_total:"0",
	status:"3",
	basket_comment:nil,
	giftwrapcode:nil,
	giftto:nil,
	giftfrom:nil,
	giftmsg:nil,
	custom6:nil,
	remote_ip_address:"71.185.216.35",
	remote_host_name:"71.185.216.35"
}

$orderitem = {
  ordernum: "12781",
  lineitem: "1",
  sku: "18492",
  description: "Nordica Men's 2015 NRGY Pro 1 Ski Boot",
  quantity: "1",
  unitprice: "389",
  unitdiscount: "0",
  extensionprice: "389",
  lineitemtax: "0",
  unittax: "0",
  giftwrapcode: nil,
  giftto: nil,
  giftfrom: nil,
  giftmsg: nil,
  dept_id: "3523",
  pf_id: "PAIEIDGMIPHKLENA",
  attr_value1: "26.5",
  attr_value2: "Green",
  attr_value3: nil,
  attr_value4: nil,
  attr_value5: nil,
  info_attr1: nil,
  info_attr2: nil,
  info_attr3: nil,
  rproitemnum: "18492"
}

$shopper = {
  shopper_id: "8B7CFAF55C39412BBC2466547B628DE0",
  first_name: "Gunnar",
  last_name: "Baldwin",
  company: nil,
  street: "375 Fairgrounds Road",
  street1: nil,
  city: "Plymouth",
  state: "NH",
  zip: "3264",
  country: "USA",
  phone: "6032631836",
  fax: nil,
  email: "meadowside@roadrunner.com",
  rpro_cust_sid: "PAIEIDNIOGNODGOL",
  shopper_pref_1: "NO",
  shopper_pref_2: "NO",
  shopper_pref_3: "NO",
  shopper_pref_4: "0",
  shopper_text_info: nil,
  date_created: "07/21/15",
  preferred_code: nil
}

#$this_map = build_map($csv_table)
#$this_schema = $db_schema[:"#{$db_table}"]
#$key = $this_schema[:KEY]
#$key = $key.split("-") if $key.match("-")
#$db = SQLite3::Database.new "#{$db_file}"
